name: Build and Release on Push to Master

on:
  push:
    branches:
      - master

jobs:
  release:
    strategy:
      matrix:
        node: ['12']

    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Release on GitHub
        run: npx semantic-release -p        \
          @semantic-release/commit-analyzer \
          @semantic-release/github         \
          @semantic-release/release-notes-generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: releases
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: supabase
          repo: supabase-admin-api
          excludes: prerelease, draft

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4' # The Go version to download (if necessary) and use.

      - run: make deps

      - run: make all

      - run: tar -czvf supabase-admin-api-${{ steps.releases.outputs.release }}.tar.gz supabase-admin-api

      - uses: actions/upload-artifact@v1
        with:
          name: ./supabase-admin-api-${{ steps.releases.outputs.release }}.tar.gz
          path: supabase-admin-api-${{ steps.releases.outputs.release }}.tar.gz

