name: Build and Release on Push to Master

on:
  push:
    branches:
      - master

jobs:
  release:
    strategy:
      matrix:
        node: ['12']

    outputs:
      status: ${{ steps.pre-release.outputs.release != steps.post-release.outputs.release }}

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - id: pre-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: supabase
          repo: supabase-admin-api
          excludes: prerelease, draft

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Release on GitHub
        id: github-release
        run: npx semantic-release -p        \
          @semantic-release/commit-analyzer \
          @semantic-release/github         \
          @semantic-release/release-notes-generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: post-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: supabase
          repo: supabase-admin-api
          excludes: prerelease, draft

      

  deploy:
    needs: release
    runs-on: ubuntu-20.04
    if: success() && needs.release.outputs.status == 'true'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
